//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace RepositoryPattern.DAL.XPO.RepositoryPattern
{

    public partial class StudentXPO : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fGrade;
        public int Grade
        {
            get { return fGrade; }
            set { SetPropertyValue<int>(nameof(Grade), ref fGrade, value); }
        }
        bool fPass;
        public bool Pass
        {
            get { return fPass; }
            set { SetPropertyValue<bool>(nameof(Pass), ref fPass, value); }
        }
        UserXPO fAddedBy;
        public UserXPO AddedBy
        {
            get { return fAddedBy; }
            set { SetPropertyValue<UserXPO>(nameof(AddedBy), ref fAddedBy, value); }
        }
        UserXPO fLastUpdateBy;
        public UserXPO LastUpdateBy
        {
            get { return fLastUpdateBy; }
            set { SetPropertyValue<UserXPO>(nameof(LastUpdateBy), ref fLastUpdateBy, value); }
        }
    }

}
